version: '3.8'

services:
  db:
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "pokedex"
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    depends_on:
      - db
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/pokedex"
    ports:
      - "80:8000"